use_frameworks!

platform :ios, '8.0'

target 'ComponentModuleBCategory_Example' do
  pod 'ComponentModuleBCategory', :path => '../'

  target 'ComponentModuleBCategory_Tests' do
    inherit! :search_paths

    
  end
end
